services:
  - type: web
    name: nhs-django-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hospital_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: 1$9q(-@v+a@zr16ord@&wwwy4k_ztoce@7v0-%6%@d@x$=tfzy
      - key: DATABASE_URL
        fromDatabase:
          name: nhs-db
          property: connectionString
    plan: free
    autoDeploy: true