# Generated by Django 5.2 on 2025-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sms_gateway',
            field=models.CharField(default='default.com', help_text='e.g. vtext.com for Verizon', max_length=50),
            preserve_default=False,
        ),
    ]
