# Generated by Django 5.2 on 2025-04-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_patient_sms_gateway_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='user',
        ),
    ]
